/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetProjectsRequestOrderBy = "asc" | "desc";
export const GetProjectsRequestOrderBy = {
    Asc: "asc",
    Desc: "desc",
} as const;
