/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * - skip: Return existing record without changes
 * - replace: Replace existing record with new data
 * - enrich: Update only empty fields in existing record
 */
export type PostProjectsRequestMatchFoundStrategy = "skip" | "replace" | "enrich";

export const PostProjectsRequestMatchFoundStrategy = {
    Skip: "skip",
    Replace: "replace",
    Enrich: "enrich",
} as const;
