/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostProjectsRequestMatchBy = "title" | "primaryEmail" | "primaryPhone" | "address";

export const PostProjectsRequestMatchBy = {
    Title: "title",
    PrimaryEmail: "primaryEmail",
    PrimaryPhone: "primaryPhone",
    Address: "address",
} as const;
