/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";
import { Comment } from "../../../types/Comment";

export const Response: core.serialization.Schema<
    serializers.comments.listProjectComments.Response.Raw,
    CoperniqApi.Comment[]
> = core.serialization.list(Comment);

export declare namespace Response {
    export type Raw = Comment.Raw[];
}
