/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as CoperniqApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const UserInvite: core.serialization.Schema<serializers.UserInvite.Raw, CoperniqApi.UserInvite> =
    core.serialization.object({
        email: core.serialization.string(),
        roleId: core.serialization.string(),
    });

export declare namespace UserInvite {
    export interface Raw {
        email: string;
        roleId: string;
    }
}
