/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetRequestsRequestOrderBy = "asc" | "desc";
export const GetRequestsRequestOrderBy = {
    Asc: "asc",
    Desc: "desc",
} as const;
