/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostRequestsRequestMatchBy = "title" | "primaryEmail" | "primaryPhone" | "address";
export const PostRequestsRequestMatchBy = {
    Title: "title",
    PrimaryEmail: "primaryEmail",
    PrimaryPhone: "primaryPhone",
    Address: "address",
} as const;
