/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as CoperniqApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const PostProjectsProjectIdWorkOrdersRequest: core.serialization.Schema<
    serializers.PostProjectsProjectIdWorkOrdersRequest.Raw,
    CoperniqApi.PostProjectsProjectIdWorkOrdersRequest
> = core.serialization.object({
    templateId: core.serialization.string(),
    title: core.serialization.string(),
    description: core.serialization.string().optional(),
    priority: core.serialization.number().optional(),
    startDate: core.serialization.date().optional(),
    endDate: core.serialization.date().optional(),
});

export declare namespace PostProjectsProjectIdWorkOrdersRequest {
    export interface Raw {
        templateId: string;
        title: string;
        description?: string | null;
        priority?: number | null;
        startDate?: string | null;
        endDate?: string | null;
    }
}
