/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";
import { Team } from "../../../types/Team";

export const Response: core.serialization.Schema<serializers.users.listTeams.Response.Raw, CoperniqApi.Team[]> =
    core.serialization.list(Team);

export declare namespace Response {
    type Raw = Team.Raw[];
}
