/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetPropertiesRequest {
    /**
     * Record type (e.g., project, client, request)
     */
    recordType?: string;
}
