/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class CoperniqApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, CoperniqApiTimeoutError.prototype);
    }
}
