/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface PatchRequestsRequestIdRequest {
    /**
     * Whether to allow creation of new dropdown options during record creation
     */
    allowNewOptions?: boolean;
    body?: unknown;
}
