/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../../../../index";

/**
 * @example
 *     {
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface PostRequestsRequest {
    /**
     * Whether to allow creation of new dropdown options during record creation
     */
    allowNewOptions?: boolean;
    /**
     * Field to use for matching existing records
     */
    matchBy?: CoperniqApi.PostRequestsRequestMatchBy;
    /**
     * Strategy to use when a match is found
     */
    matchFoundStrategy?: CoperniqApi.PostRequestsRequestMatchFoundStrategy;
    body?: unknown;
}
