/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetContactsRequestOrderBy = "asc" | "desc";

export const GetContactsRequestOrderBy = {
    Asc: "asc",
    Desc: "desc",
} as const;
