/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";
import { File_ } from "../../../types/File_";

export const Response: core.serialization.Schema<serializers.files.getClientFiles.Response.Raw, CoperniqApi.File_[]> =
    core.serialization.list(File_);

export declare namespace Response {
    export type Raw = File_.Raw[];
}
