/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Client type
 */
export type ClientCreateType = "RESIDENTIAL" | "COMMERCIAL";

export const ClientCreateType = {
    Residential: "RESIDENTIAL",
    Commercial: "COMMERCIAL",
} as const;
