/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetClientsRequestOrderBy = "asc" | "desc";

export const GetClientsRequestOrderBy = {
    Asc: "asc",
    Desc: "desc",
} as const;
