/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";
import { Workflow } from "../../../types/Workflow";

export const Response: core.serialization.Schema<
    serializers.workflows.listWorkflows.Response.Raw,
    CoperniqApi.Workflow[]
> = core.serialization.list(Workflow);

export declare namespace Response {
    export type Raw = Workflow.Raw[];
}
