/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         token: "token",
 *         destinationUsername: "destination_username"
 *     }
 */
export interface GetImport2ConfirmFullMigrationRequest {
    /**
     * Migration token
     */
    token: string;
    /**
     * Username of destination account
     */
    destinationUsername: string;
}
