/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../../../../index";

/**
 * @example
 *     {
 *         body: {
 *             title: "title",
 *             address: "address",
 *             trades: ["trades"]
 *         }
 *     }
 */
export interface PostProjectsRequest {
    /**
     * Whether to allow creation of new dropdown options during record creation
     */
    allowNewOptions?: boolean;
    /**
     * Field to use for matching existing records
     */
    matchBy?: CoperniqApi.PostProjectsRequestMatchBy;
    /**
     * Strategy to use when a match is found
     */
    matchFoundStrategy?: CoperniqApi.PostProjectsRequestMatchFoundStrategy;
    body: CoperniqApi.ProjectCreate;
}
