/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ProjectUpdate {
    /**
     * Whether to allow creation of new dropdown options during record creation
     */
    allowNewOptions?: boolean;
    /** Project title/name */
    title?: string;
    /** Project description */
    description?: string;
    /** Project location/address */
    address?: string;
    /** Array of trade types */
    trades?: string[];
    /** ID of associated client */
    clientId?: string;
    /** ID of associated workflow */
    workflowId?: string;
    /** Project value */
    value?: number;
    /** Project size */
    size?: number;
    status?: CoperniqApi.ProjectStatus;
    /** Primary contact email */
    primaryEmail?: string;
    /** Primary contact phone */
    primaryPhone?: string;
    /** Custom fields */
    custom?: Record<string, unknown>;
}
