/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../../../../index";

/**
 * @example
 *     {
 *         title: "title",
 *         address: "address"
 *     }
 */
export interface ClientCreate {
    /**
     * Whether to allow creation of new dropdown options during record creation
     */
    allowNewOptions?: boolean;
    /**
     * Field to use for matching existing records
     */
    matchBy?: CoperniqApi.PostClientsRequestMatchBy;
    /**
     * Strategy to use when a match is found
     */
    matchFoundStrategy?: CoperniqApi.PostClientsRequestMatchFoundStrategy;
    /** Client name */
    title: string;
    /** Client description */
    description?: string;
    /** Client location/address */
    address: string;
    /** Client type */
    type?: CoperniqApi.ClientCreateType;
    /** Primary contact email */
    primaryEmail?: string;
    /** Primary contact phone */
    primaryPhone?: string;
    /** Custom fields */
    custom?: Record<string, unknown>;
}
