/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../../../../index";

/**
 * @example
 *     {}
 */
export interface GetClientsRequest {
    /**
     * Number of items per page (max 100)
     */
    pageSize?: number;
    /**
     * Page number (1-based)
     */
    page?: number;
    /**
     * Filter items updated after this timestamp (ISO 8601)
     */
    updatedAfter?: Date;
    /**
     * Filter items updated before this timestamp (ISO 8601)
     */
    updatedBefore?: Date;
    /**
     * Sort order for results
     */
    orderBy?: CoperniqApi.GetClientsRequestOrderBy;
    /**
     * Whether to include virtual properties in the response. Defaults to false unless explicitly set to true.
     */
    includeVirtualProperties?: boolean;
    /**
     * Full text search query
     */
    q?: string;
    /**
     * Title search query
     */
    title?: string;
    /**
     * Address search query
     */
    address?: string;
    /**
     * Contact name search query
     */
    primaryName?: string;
    /**
     * Contact phone search query
     */
    primaryPhone?: string;
    /**
     * Contact email search query
     */
    primaryEmail?: string;
}
