/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetClientsClientIdRequest {
    /**
     * Whether to include virtual properties in the response. Defaults to false unless explicitly set to true.
     */
    includeVirtualProperties?: boolean;
}
