/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetComapniesRequest {
    /**
     * Page number
     */
    page?: number;
    /**
     * Number of items per page
     */
    pageSize?: number;
    /**
     * Field to sort by
     */
    orderBy?: string;
}
