/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

export interface BadRequestErrorBody {
    message?: string;
    code?: CoperniqApi.BadRequestErrorBodyCode;
    /** Field that caused the validation error (if applicable) */
    field?: string;
}
