/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of client (residential or commercial)
 */
export type ClientType = "RESIDENTIAL" | "COMMERCIAL";

export const ClientType = {
    Residential: "RESIDENTIAL",
    Commercial: "COMMERCIAL",
} as const;
