/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

export interface Client extends CoperniqApi.BaseRecord {
    /** Type of client (residential or commercial) */
    type?: CoperniqApi.ClientType;
}
