/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CommentAuthor {
    /** Author identifier */
    id?: number;
    /** Author first name */
    firstName?: string;
    /** Author last name */
    lastName?: string;
    /** Author email */
    email?: string;
    /** Author phone */
    phone?: string;
    /** Author avatar URL */
    avatarUrl?: string;
}
