/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

export interface Comment {
    /** Comment identifier */
    id: number;
    /** Comment text content */
    body: string;
    /** Creation timestamp */
    createdAt: Date;
    /** Last update timestamp */
    updatedAt: Date;
    author: CoperniqApi.CommentAuthor;
}
