/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

export interface Company {
    /** Company identifier */
    id?: number;
    /** Company name */
    name?: string;
    /** Company address */
    address?: string;
    /** Company website */
    website?: string;
    /** Company logo URL */
    logoUrl?: string;
    /** Company timezone */
    timezone?: string;
    /** Creation timestamp */
    createdAt?: Date;
    /** Last update timestamp */
    updatedAt?: Date;
    phones?: CoperniqApi.CompanyPhonesItem[];
}
