/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CompanyPhonesItem {
    /** Phone number */
    phone?: string;
    /** Whether the phone number is permanently deleted */
    isPermanentlyDeleted?: boolean;
    /** Forwarding phone number */
    forwardingPhone?: string;
    /** Phone alias */
    alias?: string;
}
