/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Error code
 */
export type ErrorCode = "VALIDATION_ERROR" | "NOT_FOUND" | "UNAUTHORIZED" | "BAD_REQUEST";
export const ErrorCode = {
    ValidationError: "VALIDATION_ERROR",
    NotFound: "NOT_FOUND",
    Unauthorized: "UNAUTHORIZED",
    BadRequest: "BAD_REQUEST",
} as const;
