/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

export interface Error_ {
    /** Error code */
    code?: CoperniqApi.ErrorCode;
    /** Human-readable error message explaining what went wrong */
    message?: string;
    /** Name of the field that failed validation (only present for VALIDATION_ERROR) */
    field?: string;
}
