/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FileMetaData {
    /** Access control level */
    acl: string;
    /** GPS coordinates if applicable */
    gps?: Record<string, unknown>;
    /** File size in bytes */
    size: number;
    /** User who uploaded the file */
    userId: number;
    /** MIME type of the file */
    mimeType: string;
    /** File extension */
    extention: string;
    /** Original file name */
    originalName: string;
    /** URL to the thumbnail version */
    thumbnailUrl?: string;
    /** Generated unique file name */
    generatedName: string;
    /** Generated thumbnail file name */
    thumbnailName?: string;
    /** Original request file name */
    requestFileName?: string;
}
