/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FileCreatedByUser {
    /** User identifier */
    id: number;
    /** User's first name */
    firstName: string;
    /** User's last name */
    lastName: string;
}
