/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

export interface File_ {
    /** File identifier */
    id: number;
    /** File name */
    name: string;
    /** URL to download the file */
    downloadUrl: string;
    /** File type */
    type: string;
    /** Last update timestamp */
    updatedAt: Date;
    /** Creation timestamp */
    createdAt: Date;
    /** Company identifier */
    companyId: number;
    metaData: CoperniqApi.FileMetaData;
    /** File source (e.g., INTERNAL) */
    source: string;
    createdByUser: CoperniqApi.FileCreatedByUser;
}
