/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Current SLA violation status
 */
export type ProjectStageSlaStatus = "VIOLATED" | "NON_VIOLATED";
export const ProjectStageSlaStatus = {
    Violated: "VIOLATED",
    NonViolated: "NON_VIOLATED",
} as const;
