/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of the project:
 * * `ACTIVE` - Project is active and in progress
 * * `ON_HOLD` - Project is temporarily paused
 * * `CANCELLED` - Project has been cancelled
 * * `COMPLETED` - Project has been completed
 */
export type ProjectStatus = "ACTIVE" | "ON_HOLD" | "CANCELLED" | "COMPLETED";

export const ProjectStatus = {
    Active: "ACTIVE",
    OnHold: "ON_HOLD",
    Cancelled: "CANCELLED",
    Completed: "COMPLETED",
} as const;
