/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

/**
 * Current stage information
 */
export interface ProjectStage {
    /** Stage identifier */
    id?: number;
    /** Stage name */
    name?: string;
    /** Stage type */
    type?: string;
    /** Stage scope */
    scope?: string;
    /** Red SLA threshold in days */
    redSla?: number;
    /** Yellow SLA threshold in days */
    yellowSla?: number;
    /** Number of days in current stage */
    timeInStageDays?: number;
    /** Current SLA violation status */
    slaStatus?: CoperniqApi.ProjectStageSlaStatus;
}
