/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

export interface Project extends CoperniqApi.BaseRecord {
    /** Array of trade types */
    trades?: string[];
    /** Project value */
    value?: number;
    /** Project size */
    size?: number;
    /** Associated workflow ID */
    workflowId?: number;
    /** Associated client ID */
    clientId?: number;
    status?: CoperniqApi.ProjectStatus;
    /** Current stage information */
    stage?: CoperniqApi.ProjectStage;
}
