/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Property {
    /** Property name */
    name?: string;
    /** Property type */
    type?: string;
    /** Property key name */
    keyName?: string;
    /** Whether the property is a multiple value property */
    isMultiple?: boolean;
    /** Property options */
    options?: string[];
    /** Default value */
    defaultValue?: unknown[];
}
