/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

export interface Request extends CoperniqApi.BaseRecord {
    /** Array of trade types */
    trades?: string[];
    /** Deal value */
    value?: number;
    /** Deal size */
    size?: number;
    /** Deal confidence score (0-100) */
    confidence?: number;
    /** Associated workflow ID */
    workflowId?: number;
    /** Associated client ID */
    clientId?: number;
    /** Request status */
    status?: string;
}
