/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Role {
    /** Unique identifier */
    id: string;
    /** Role name */
    name: string;
    /** Whether the role is active */
    active: boolean;
}
