/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

export interface Team {
    id?: number;
    name?: string;
    members?: CoperniqApi.User[];
}
