/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

export interface User {
    /** Unique identifier */
    id: string;
    /** Email address */
    email: string;
    /** First name */
    firstName: string;
    /** Last name */
    lastName: string;
    /** Phone number */
    phone?: string;
    role: CoperniqApi.UserRole;
}
