/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status identifier
 */
export type WorkOrderStatusesItemStatus = "QUEUED" | "WAITING" | "CANCELLED" | "WORKING" | "COMPLETED";
export const WorkOrderStatusesItemStatus = {
    Queued: "QUEUED",
    Waiting: "WAITING",
    Cancelled: "CANCELLED",
    Working: "WORKING",
    Completed: "COMPLETED",
} as const;
