/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WorkOrder {
    /** Work order identifier */
    id?: number;
    /** Work order title */
    title?: string;
    /** Work order description */
    description?: string;
    /** Priority level */
    priority?: number;
    /** Scheduled start date */
    startDate?: Date;
    /** Scheduled end date */
    endDate?: Date;
    /** Template identifier */
    templateId?: number;
    /** Work order status */
    status?: string;
    /** Associated project identifier */
    projectId?: number;
}
