/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

/**
 * Work order status
 */
export interface WorkOrderStatus {
    /** Status identifier */
    id: string;
    /** Human readable status label */
    label: string;
    /** User who last updated the status. Only shown when status is COMPLETED or CANCELLED. */
    updatedBy?: CoperniqApi.WorkOrderStatusUpdatedBy;
}
