/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

export interface Workflow {
    /** Workflow identifier */
    id?: number;
    /** Workflow name */
    name?: string;
    /** Workflow type */
    type?: string;
    /** Last update timestamp */
    updatedAt?: Date;
    /** Creation timestamp */
    createdAt?: Date;
    stages?: CoperniqApi.WorkflowStagesItem[];
}
