/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

export interface WorkOrder {
    /** Work order identifier */
    id?: number;
    /** Work order title */
    title?: string;
    /** Work order description */
    description?: string;
    /** Priority level */
    priority?: number;
    /** Scheduled start date */
    startDate?: Date;
    /** Scheduled end date */
    endDate?: Date;
    /** Template identifier */
    templateId?: number;
    /** Work order status */
    status?: CoperniqApi.WorkOrderStatus;
    /** History of status changes and time spent in each status */
    statuses?: CoperniqApi.WorkOrderStatusesItem[];
    /** Associated project identifier */
    projectId?: number;
}
