/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * User who last updated the status. Only shown when status is COMPLETED or CANCELLED.
 */
export interface WorkOrderStatusUpdatedBy {
    /** User identifier */
    id: number;
    /** User's first name */
    firstName: string;
    /** User's last name */
    lastName: string;
}
