/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WorkOrderTemplate {
    /** Template identifier */
    id?: number;
    /** Template name */
    name?: string;
    /** Template description */
    description?: string;
}
