/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WorkflowStagesItem {
    /** Stage name */
    name?: string;
    /** Stage type */
    type?: string;
    /** Stage scope */
    scope?: string;
    /** Stage description */
    description?: string;
    /** Red SLA (Service Level Agreement) in days */
    redSla?: number;
    /** Yellow SLA (Service Level Agreement) in days */
    yellowSla?: number;
}
