/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../index";

export interface WorkOrderStatusesItem {
    /** Number of times this status was entered */
    count: string;
    /** When the status ended */
    endedAt: Date;
    /** Time spent in this status in seconds */
    spentTime: number;
    /** When the status started */
    startedAt: Date;
    /** Status identifier */
    status: CoperniqApi.WorkOrderStatusesItemStatus;
}
