/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         templateId: "templateId",
 *         title: "title"
 *     }
 */
export interface PostProjectsProjectIdWorkOrdersRequest {
    /** Template to use for the work order */
    templateId: string;
    /** Work order title */
    title: string;
    /** Work order description */
    description?: string;
    /** Priority level */
    priority?: number;
    /** Scheduled start date */
    startDate?: Date;
    /** Scheduled end date */
    endDate?: Date;
}
