/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";
import { WorkOrderTemplate } from "../../../types/WorkOrderTemplate";

export const Response: core.serialization.Schema<
    serializers.workOrders.listWorkOrderTemplates.Response.Raw,
    CoperniqApi.WorkOrderTemplate[]
> = core.serialization.list(WorkOrderTemplate);

export declare namespace Response {
    type Raw = WorkOrderTemplate.Raw[];
}
