/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";
import { WorkOrder } from "../../../types/WorkOrder";

export const Response: core.serialization.Schema<
    serializers.workOrders.listWorkOrders.Response.Raw,
    CoperniqApi.WorkOrder[]
> = core.serialization.list(WorkOrder);

export declare namespace Response {
    type Raw = WorkOrder.Raw[];
}
