/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostProjectsRequestMatchBy: core.serialization.Schema<
    serializers.PostProjectsRequestMatchBy.Raw,
    CoperniqApi.PostProjectsRequestMatchBy
> = core.serialization.enum_(["title", "primaryEmail", "primaryPhone", "address"]);

export declare namespace PostProjectsRequestMatchBy {
    type Raw = "title" | "primaryEmail" | "primaryPhone" | "address";
}
