/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";
import { Contact } from "../../../types/Contact";

export const Response: core.serialization.Schema<
    serializers.contacts.listContacts.Response.Raw,
    CoperniqApi.Contact[]
> = core.serialization.list(Contact);

export declare namespace Response {
    export type Raw = Contact.Raw[];
}
