/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetContactsRequestOrderBy: core.serialization.Schema<
    serializers.GetContactsRequestOrderBy.Raw,
    CoperniqApi.GetContactsRequestOrderBy
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace GetContactsRequestOrderBy {
    export type Raw = "asc" | "desc";
}
