/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";
import { Company } from "../../../types/Company";

export const Response: core.serialization.Schema<
    serializers.companies.listCompanies.Response.Raw,
    CoperniqApi.Company[]
> = core.serialization.list(Company);

export declare namespace Response {
    export type Raw = Company.Raw[];
}
