/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetProjectsProjectIdWorkOrdersRequestOrderBy = "asc" | "desc";

export const GetProjectsProjectIdWorkOrdersRequestOrderBy = {
    Asc: "asc",
    Desc: "desc",
} as const;
