/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetWorkOrdersRequestOrderBy = "asc" | "desc";

export const GetWorkOrdersRequestOrderBy = {
    Asc: "asc",
    Desc: "desc",
} as const;
