/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";

export const ClientCreateType: core.serialization.Schema<
    serializers.ClientCreateType.Raw,
    CoperniqApi.ClientCreateType
> = core.serialization.enum_(["RESIDENTIAL", "COMMERCIAL"]);

export declare namespace ClientCreateType {
    type Raw = "RESIDENTIAL" | "COMMERCIAL";
}
