/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostClientsRequestMatchFoundStrategy: core.serialization.Schema<
    serializers.PostClientsRequestMatchFoundStrategy.Raw,
    CoperniqApi.PostClientsRequestMatchFoundStrategy
> = core.serialization.enum_(["skip", "replace", "enrich"]);

export declare namespace PostClientsRequestMatchFoundStrategy {
    export type Raw = "skip" | "replace" | "enrich";
}
