/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";

export const PostClientsRequestMatchBy: core.serialization.Schema<
    serializers.PostClientsRequestMatchBy.Raw,
    CoperniqApi.PostClientsRequestMatchBy
> = core.serialization.enum_(["title", "primaryEmail", "primaryPhone", "address"]);

export declare namespace PostClientsRequestMatchBy {
    export type Raw = "title" | "primaryEmail" | "primaryPhone" | "address";
}
