/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CoperniqApi from "../../../index";

export interface GetPropertiesResponse {
    projects?: CoperniqApi.Property[];
    clients?: CoperniqApi.Property[];
    requests?: CoperniqApi.Property[];
}
