/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const ApiKeyResponse: core.serialization.ObjectSchema<
    serializers.ApiKeyResponse.Raw,
    CoperniqApi.ApiKeyResponse
> = core.serialization.object({
    apiKey: core.serialization.string(),
    expiresAt: core.serialization.date().optional(),
});

export declare namespace ApiKeyResponse {
    interface Raw {
        apiKey: string;
        expiresAt?: string | null;
    }
}
