/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const BadRequestErrorBody: core.serialization.ObjectSchema<
    serializers.BadRequestErrorBody.Raw,
    CoperniqApi.BadRequestErrorBody
> = core.serialization.object({
    message: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
});

export declare namespace BadRequestErrorBody {
    interface Raw {
        message?: string | null;
        code?: string | null;
    }
}
