/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";
import { BadRequestErrorBodyCode } from "./BadRequestErrorBodyCode";

export const BadRequestErrorBody: core.serialization.ObjectSchema<
    serializers.BadRequestErrorBody.Raw,
    CoperniqApi.BadRequestErrorBody
> = core.serialization.object({
    message: core.serialization.string().optional(),
    code: BadRequestErrorBodyCode.optional(),
    field: core.serialization.string().optional(),
});

export declare namespace BadRequestErrorBody {
    export interface Raw {
        message?: string | null;
        code?: BadRequestErrorBodyCode.Raw | null;
        field?: string | null;
    }
}
