/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const BaseRecord: core.serialization.ObjectSchema<serializers.BaseRecord.Raw, CoperniqApi.BaseRecord> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        createdAt: core.serialization.date().optional(),
        updatedAt: core.serialization.date().optional(),
        title: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
        address: core.serialization.string().optional(),
        isActive: core.serialization.boolean().optional(),
        companyId: core.serialization.number().optional(),
        primaryEmail: core.serialization.string().optional(),
        primaryPhone: core.serialization.string().optional(),
        number: core.serialization.number().optional(),
        custom: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    });

export declare namespace BaseRecord {
    interface Raw {
        id?: number | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        title?: string | null;
        description?: string | null;
        address?: string | null;
        isActive?: boolean | null;
        companyId?: number | null;
        primaryEmail?: string | null;
        primaryPhone?: string | null;
        number?: number | null;
        custom?: Record<string, unknown> | null;
    }
}
