/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";
import { ClientType } from "./ClientType";
import { BaseRecord } from "./BaseRecord";

export const Client: core.serialization.ObjectSchema<serializers.Client.Raw, CoperniqApi.Client> = core.serialization
    .object({
        type: ClientType.optional(),
    })
    .extend(BaseRecord);

export declare namespace Client {
    export interface Raw extends BaseRecord.Raw {
        type?: ClientType.Raw | null;
    }
}
