/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const ClientType: core.serialization.Schema<serializers.ClientType.Raw, CoperniqApi.ClientType> =
    core.serialization.enum_(["RESIDENTIAL", "COMMERCIAL"]);

export declare namespace ClientType {
    export type Raw = "RESIDENTIAL" | "COMMERCIAL";
}
