/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const CommentAuthor: core.serialization.ObjectSchema<serializers.CommentAuthor.Raw, CoperniqApi.CommentAuthor> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        firstName: core.serialization.string().optional(),
        lastName: core.serialization.string().optional(),
        email: core.serialization.string().optional(),
        phone: core.serialization.string().optional(),
        avatarUrl: core.serialization.string().optional(),
    });

export declare namespace CommentAuthor {
    export interface Raw {
        id?: number | null;
        firstName?: string | null;
        lastName?: string | null;
        email?: string | null;
        phone?: string | null;
        avatarUrl?: string | null;
    }
}
