/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const CommentUpdate: core.serialization.ObjectSchema<serializers.CommentUpdate.Raw, CoperniqApi.CommentUpdate> =
    core.serialization.object({
        body: core.serialization.string(),
    });

export declare namespace CommentUpdate {
    export interface Raw {
        body: string;
    }
}
