/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";
import { CommentAuthor } from "./CommentAuthor";

export const Comment: core.serialization.ObjectSchema<serializers.Comment.Raw, CoperniqApi.Comment> =
    core.serialization.object({
        id: core.serialization.number(),
        body: core.serialization.string(),
        createdAt: core.serialization.date(),
        updatedAt: core.serialization.date(),
        author: CommentAuthor,
    });

export declare namespace Comment {
    export interface Raw {
        id: number;
        body: string;
        createdAt: string;
        updatedAt: string;
        author: CommentAuthor.Raw;
    }
}
