/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const CompanyPhonesItem: core.serialization.ObjectSchema<
    serializers.CompanyPhonesItem.Raw,
    CoperniqApi.CompanyPhonesItem
> = core.serialization.object({
    phone: core.serialization.string().optional(),
    isPermanentlyDeleted: core.serialization.boolean().optional(),
    forwardingPhone: core.serialization.string().optional(),
    alias: core.serialization.string().optional(),
});

export declare namespace CompanyPhonesItem {
    export interface Raw {
        phone?: string | null;
        isPermanentlyDeleted?: boolean | null;
        forwardingPhone?: string | null;
        alias?: string | null;
    }
}
