/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";
import { CompanyPhonesItem } from "./CompanyPhonesItem";

export const Company: core.serialization.ObjectSchema<serializers.Company.Raw, CoperniqApi.Company> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        name: core.serialization.string().optional(),
        address: core.serialization.string().optional(),
        website: core.serialization.string().optional(),
        logoUrl: core.serialization.string().optional(),
        timezone: core.serialization.string().optional(),
        createdAt: core.serialization.date().optional(),
        updatedAt: core.serialization.date().optional(),
        phones: core.serialization.list(CompanyPhonesItem).optional(),
    });

export declare namespace Company {
    export interface Raw {
        id?: number | null;
        name?: string | null;
        address?: string | null;
        website?: string | null;
        logoUrl?: string | null;
        timezone?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        phones?: CompanyPhonesItem.Raw[] | null;
    }
}
