/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const Contact: core.serialization.ObjectSchema<serializers.Contact.Raw, CoperniqApi.Contact> =
    core.serialization.object({
        id: core.serialization.string(),
        firstName: core.serialization.string(),
        lastName: core.serialization.string(),
        email: core.serialization.string().optional(),
        phone: core.serialization.string().optional(),
        createdAt: core.serialization.date(),
        updatedAt: core.serialization.date(),
    });

export declare namespace Contact {
    interface Raw {
        id: string;
        firstName: string;
        lastName: string;
        email?: string | null;
        phone?: string | null;
        createdAt: string;
        updatedAt: string;
    }
}
