/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";
import { ErrorCode } from "./ErrorCode";

export const Error_: core.serialization.ObjectSchema<serializers.Error_.Raw, CoperniqApi.Error_> =
    core.serialization.object({
        code: ErrorCode.optional(),
        message: core.serialization.string().optional(),
        field: core.serialization.string().optional(),
    });

export declare namespace Error_ {
    interface Raw {
        code?: ErrorCode.Raw | null;
        message?: string | null;
        field?: string | null;
    }
}
