/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";
import { FileMetaData } from "./FileMetaData";
import { FileCreatedByUser } from "./FileCreatedByUser";

export const File_: core.serialization.ObjectSchema<serializers.File_.Raw, CoperniqApi.File_> =
    core.serialization.object({
        id: core.serialization.number(),
        name: core.serialization.string(),
        downloadUrl: core.serialization.string(),
        type: core.serialization.string(),
        updatedAt: core.serialization.date(),
        createdAt: core.serialization.date(),
        companyId: core.serialization.number(),
        metaData: FileMetaData,
        source: core.serialization.string(),
        createdByUser: FileCreatedByUser,
    });

export declare namespace File_ {
    export interface Raw {
        id: number;
        name: string;
        downloadUrl: string;
        type: string;
        updatedAt: string;
        createdAt: string;
        companyId: number;
        metaData: FileMetaData.Raw;
        source: string;
        createdByUser: FileCreatedByUser.Raw;
    }
}
