/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const InternalServerErrorBody: core.serialization.ObjectSchema<
    serializers.InternalServerErrorBody.Raw,
    CoperniqApi.InternalServerErrorBody
> = core.serialization.object({
    message: core.serialization.string().optional(),
    code: core.serialization.stringLiteral("INTERNAL_SERVER_ERROR").optional(),
});

export declare namespace InternalServerErrorBody {
    export interface Raw {
        message?: string | null;
        code?: "INTERNAL_SERVER_ERROR" | null;
    }
}
