/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const NotFoundErrorBody: core.serialization.ObjectSchema<
    serializers.NotFoundErrorBody.Raw,
    CoperniqApi.NotFoundErrorBody
> = core.serialization.object({
    message: core.serialization.string().optional(),
    code: core.serialization.stringLiteral("NOT_FOUND").optional(),
});

export declare namespace NotFoundErrorBody {
    interface Raw {
        message?: string | null;
        code?: "NOT_FOUND" | null;
    }
}
