/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const ProjectStatus: core.serialization.Schema<serializers.ProjectStatus.Raw, CoperniqApi.ProjectStatus> =
    core.serialization.enum_(["ACTIVE", "ON_HOLD", "CANCELLED", "COMPLETED"]);

export declare namespace ProjectStatus {
    export type Raw = "ACTIVE" | "ON_HOLD" | "CANCELLED" | "COMPLETED";
}
