/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const ProjectStageSlaStatus: core.serialization.Schema<
    serializers.ProjectStageSlaStatus.Raw,
    CoperniqApi.ProjectStageSlaStatus
> = core.serialization.enum_(["VIOLATED", "NON_VIOLATED"]);

export declare namespace ProjectStageSlaStatus {
    export type Raw = "VIOLATED" | "NON_VIOLATED";
}
