/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";
import { ProjectStatus } from "./ProjectStatus";
import { BaseRecord } from "./BaseRecord";

export const Project: core.serialization.ObjectSchema<serializers.Project.Raw, CoperniqApi.Project> = core.serialization
    .object({
        trades: core.serialization.list(core.serialization.string()).optional(),
        value: core.serialization.number().optional(),
        size: core.serialization.number().optional(),
        workflowId: core.serialization.number().optional(),
        clientId: core.serialization.number().optional(),
        status: ProjectStatus.optional(),
    })
    .extend(BaseRecord);

export declare namespace Project {
    interface Raw extends BaseRecord.Raw {
        trades?: string[] | null;
        value?: number | null;
        size?: number | null;
        workflowId?: number | null;
        clientId?: number | null;
        status?: ProjectStatus.Raw | null;
    }
}
