/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const Property: core.serialization.ObjectSchema<serializers.Property.Raw, CoperniqApi.Property> =
    core.serialization.object({
        name: core.serialization.string().optional(),
        type: core.serialization.string().optional(),
        keyName: core.serialization.string().optional(),
        isMultiple: core.serialization.boolean().optional(),
        options: core.serialization.list(core.serialization.string()).optional(),
        defaultValue: core.serialization.list(core.serialization.unknown()).optional(),
    });

export declare namespace Property {
    export interface Raw {
        name?: string | null;
        type?: string | null;
        keyName?: string | null;
        isMultiple?: boolean | null;
        options?: string[] | null;
        defaultValue?: unknown[] | null;
    }
}
