/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const Role: core.serialization.ObjectSchema<serializers.Role.Raw, CoperniqApi.Role> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    active: core.serialization.boolean(),
});

export declare namespace Role {
    interface Raw {
        id: string;
        name: string;
        active: boolean;
    }
}
