/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";
import { UserRole } from "./UserRole";

export const User: core.serialization.ObjectSchema<serializers.User.Raw, CoperniqApi.User> = core.serialization.object({
    id: core.serialization.string(),
    email: core.serialization.string(),
    firstName: core.serialization.string(),
    lastName: core.serialization.string(),
    phone: core.serialization.string().optional(),
    role: UserRole,
});

export declare namespace User {
    export interface Raw {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
        phone?: string | null;
        role: UserRole.Raw;
    }
}
