/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const UserRole: core.serialization.ObjectSchema<serializers.UserRole.Raw, CoperniqApi.UserRole> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
    });

export declare namespace UserRole {
    interface Raw {
        id?: string | null;
        name?: string | null;
    }
}
