/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const WorkOrderTemplate: core.serialization.ObjectSchema<
    serializers.WorkOrderTemplate.Raw,
    CoperniqApi.WorkOrderTemplate
> = core.serialization.object({
    id: core.serialization.number().optional(),
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
});

export declare namespace WorkOrderTemplate {
    export interface Raw {
        id?: number | null;
        name?: string | null;
        description?: string | null;
    }
}
