/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";
import { WorkOrderStatusesItemStatus } from "./WorkOrderStatusesItemStatus";

export const WorkOrderStatusesItem: core.serialization.ObjectSchema<
    serializers.WorkOrderStatusesItem.Raw,
    CoperniqApi.WorkOrderStatusesItem
> = core.serialization.object({
    count: core.serialization.string(),
    endedAt: core.serialization.date(),
    spentTime: core.serialization.number(),
    startedAt: core.serialization.date(),
    status: WorkOrderStatusesItemStatus,
});

export declare namespace WorkOrderStatusesItem {
    export interface Raw {
        count: string;
        endedAt: string;
        spentTime: number;
        startedAt: string;
        status: WorkOrderStatusesItemStatus.Raw;
    }
}
