/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const WorkflowStagesItem: core.serialization.ObjectSchema<
    serializers.WorkflowStagesItem.Raw,
    CoperniqApi.WorkflowStagesItem
> = core.serialization.object({
    name: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
    scope: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    redSla: core.serialization.number().optional(),
    yellowSla: core.serialization.number().optional(),
});

export declare namespace WorkflowStagesItem {
    export interface Raw {
        name?: string | null;
        type?: string | null;
        scope?: string | null;
        description?: string | null;
        redSla?: number | null;
        yellowSla?: number | null;
    }
}
