/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";
import { WorkOrderStatusUpdatedBy } from "./WorkOrderStatusUpdatedBy";

export const WorkOrderStatus: core.serialization.ObjectSchema<
    serializers.WorkOrderStatus.Raw,
    CoperniqApi.WorkOrderStatus
> = core.serialization.object({
    id: core.serialization.string(),
    label: core.serialization.string(),
    updatedBy: WorkOrderStatusUpdatedBy.optional(),
});

export declare namespace WorkOrderStatus {
    export interface Raw {
        id: string;
        label: string;
        updatedBy?: WorkOrderStatusUpdatedBy.Raw | null;
    }
}
