/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";

export const WorkOrderStatusesItemStatus: core.serialization.Schema<
    serializers.WorkOrderStatusesItemStatus.Raw,
    CoperniqApi.WorkOrderStatusesItemStatus
> = core.serialization.enum_(["QUEUED", "WAITING", "CANCELLED", "WORKING", "COMPLETED"]);

export declare namespace WorkOrderStatusesItemStatus {
    export type Raw = "QUEUED" | "WAITING" | "CANCELLED" | "WORKING" | "COMPLETED";
}
