/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as CoperniqApi from "../../api/index";
import * as core from "../../core";
import { WorkflowStagesItem } from "./WorkflowStagesItem";

export const Workflow: core.serialization.ObjectSchema<serializers.Workflow.Raw, CoperniqApi.Workflow> =
    core.serialization.object({
        id: core.serialization.number().optional(),
        name: core.serialization.string().optional(),
        type: core.serialization.string().optional(),
        updatedAt: core.serialization.date().optional(),
        createdAt: core.serialization.date().optional(),
        stages: core.serialization.list(WorkflowStagesItem).optional(),
    });

export declare namespace Workflow {
    export interface Raw {
        id?: number | null;
        name?: string | null;
        type?: string | null;
        updatedAt?: string | null;
        createdAt?: string | null;
        stages?: WorkflowStagesItem.Raw[] | null;
    }
}
