/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as CoperniqApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const ContactUpdate: core.serialization.Schema<serializers.ContactUpdate.Raw, CoperniqApi.ContactUpdate> =
    core.serialization.object({
        firstName: core.serialization.string().optional(),
        lastName: core.serialization.string().optional(),
        email: core.serialization.string().optional(),
        phone: core.serialization.string().optional(),
    });

export declare namespace ContactUpdate {
    interface Raw {
        firstName?: string | null;
        lastName?: string | null;
        email?: string | null;
        phone?: string | null;
    }
}
