/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as CoperniqApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const ContactCreate: core.serialization.Schema<serializers.ContactCreate.Raw, CoperniqApi.ContactCreate> =
    core.serialization.object({
        firstName: core.serialization.string(),
        lastName: core.serialization.string(),
        email: core.serialization.string().optional(),
        phone: core.serialization.string().optional(),
    });

export declare namespace ContactCreate {
    interface Raw {
        firstName: string;
        lastName: string;
        email?: string | null;
        phone?: string | null;
    }
}
