/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as CoperniqApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const ContactCreate: core.serialization.Schema<serializers.ContactCreate.Raw, CoperniqApi.ContactCreate> =
    core.serialization.object({
        name: core.serialization.string(),
        phones: core.serialization.list(core.serialization.string()).optional(),
        emails: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace ContactCreate {
    export interface Raw {
        name: string;
        phones?: string[] | null;
        emails?: string[] | null;
    }
}
