/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         firstName: "firstName",
 *         lastName: "lastName"
 *     }
 */
export interface ContactCreate {
    /** Contact's first name */
    firstName: string;
    /** Contact's last name */
    lastName: string;
    /** Contact's email address */
    email?: string;
    /** Contact's phone number */
    phone?: string;
}
