/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetProjectsProjectIdWorkOrdersRequestOrderBy: core.serialization.Schema<
    serializers.GetProjectsProjectIdWorkOrdersRequestOrderBy.Raw,
    CoperniqApi.GetProjectsProjectIdWorkOrdersRequestOrderBy
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace GetProjectsProjectIdWorkOrdersRequestOrderBy {
    export type Raw = "asc" | "desc";
}
