/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetWorkOrdersRequestOrderBy: core.serialization.Schema<
    serializers.GetWorkOrdersRequestOrderBy.Raw,
    CoperniqApi.GetWorkOrdersRequestOrderBy
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace GetWorkOrdersRequestOrderBy {
    type Raw = "asc" | "desc";
}
