/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Authentication } from "./api/resources/authentication/client/Client";
import { Projects } from "./api/resources/projects/client/Client";
import { Clients } from "./api/resources/clients/client/Client";
import { Comments } from "./api/resources/comments/client/Client";
import { WorkOrders } from "./api/resources/workOrders/client/Client";
import { Requests } from "./api/resources/requests/client/Client";
import { Contacts } from "./api/resources/contacts/client/Client";
import { Users } from "./api/resources/users/client/Client";

export declare namespace CoperniqApiClient {
    interface Options {
        environment?: core.Supplier<environments.CoperniqApiEnvironment | string>;
        apiKey: core.Supplier<string>;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
    }
}

export class CoperniqApiClient {
    constructor(protected readonly _options: CoperniqApiClient.Options) {}

    protected _authentication: Authentication | undefined;

    public get authentication(): Authentication {
        return (this._authentication ??= new Authentication(this._options));
    }

    protected _projects: Projects | undefined;

    public get projects(): Projects {
        return (this._projects ??= new Projects(this._options));
    }

    protected _clients: Clients | undefined;

    public get clients(): Clients {
        return (this._clients ??= new Clients(this._options));
    }

    protected _comments: Comments | undefined;

    public get comments(): Comments {
        return (this._comments ??= new Comments(this._options));
    }

    protected _workOrders: WorkOrders | undefined;

    public get workOrders(): WorkOrders {
        return (this._workOrders ??= new WorkOrders(this._options));
    }

    protected _requests: Requests | undefined;

    public get requests(): Requests {
        return (this._requests ??= new Requests(this._options));
    }

    protected _contacts: Contacts | undefined;

    public get contacts(): Contacts {
        return (this._contacts ??= new Contacts(this._options));
    }

    protected _users: Users | undefined;

    public get users(): Users {
        return (this._users ??= new Users(this._options));
    }
}
