/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const CoperniqApiEnvironment = {
    Default: "https://api.coperniq.io/v1",
} as const;

export type CoperniqApiEnvironment = typeof CoperniqApiEnvironment.Default;
