/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         email: "email",
 *         roleId: "roleId"
 *     }
 */
export interface UserInvite {
    /** Email address of user to invite */
    email: string;
    /** Role to assign to the user */
    roleId: string;
}
