/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";
import { Request } from "../../../types/Request";

export const Response: core.serialization.Schema<
    serializers.requests.listRequests.Response.Raw,
    CoperniqApi.Request[]
> = core.serialization.list(Request);

export declare namespace Response {
    export type Raw = Request.Raw[];
}
