/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";
import { ProjectCreate } from "../../../types/ProjectCreate";
import { Project } from "../../../types/Project";

export const Request: core.serialization.Schema<
    serializers.projects.importProjects.Request.Raw,
    CoperniqApi.ProjectCreate[]
> = core.serialization.list(ProjectCreate);

export declare namespace Request {
    export type Raw = ProjectCreate.Raw[];
}

export const Response: core.serialization.Schema<
    serializers.projects.importProjects.Response.Raw,
    CoperniqApi.Project[]
> = core.serialization.list(Project);

export declare namespace Response {
    export type Raw = Project.Raw[];
}
