/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";
import { Project } from "../../../types/Project";

export const Response: core.serialization.Schema<
    serializers.projects.listProjects.Response.Raw,
    CoperniqApi.Project[]
> = core.serialization.list(Project);

export declare namespace Response {
    type Raw = Project.Raw[];
}
