/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as CoperniqApi from "../../../../api/index";
import * as core from "../../../../core";

export const GetRequestsRequestOrderBy: core.serialization.Schema<
    serializers.GetRequestsRequestOrderBy.Raw,
    CoperniqApi.GetRequestsRequestOrderBy
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace GetRequestsRequestOrderBy {
    type Raw = "asc" | "desc";
}
